/** Static paths under /public/may-beauty. Run `npm run fetch-assets` to re-download from Figma and emit WebP. */
export const figmaAssets = {
  gradient: "/may-beauty/gradient.webp",
  sku: "/may-beauty/sku.webp",
  podium: "/may-beauty/podium.webp",
  gradientChallengeBenefit: "/may-beauty/gradient-challenge-benefit.webp",
  gradientMobile: "/may-beauty/gradient-mobile.webp",
  skuMobile: "/may-beauty/sku-mobile.webp",
  headerLogo: "/may-beauty/header-logo.webp",
  heroFullDesktop: "/assets/hero/hero-desktop-full.webp",
  heroFullMobile: "/assets/hero/hero-mobile-full.webp",
  speakersSection: "/may-beauty/speaker-section.webp",
  speakersSectionMobile: "/may-beauty/speaker-section-mobile.webp",
  challengesSection: "/may-beauty/challenges-section.webp",
  challengesSectionMobile: "/may-beauty/challenges-section-mobile.webp",
  benefitsSection: "/may-beauty/benefits-section.webp",
  benefitsSectionMobile: "/may-beauty/benefits-section-mobile.webp",
  agendaSection: "/may-beauty/agenda-section.webp",
  agendaSectionMobile: "/may-beauty/agenda-section-mobile.webp",
} as const;
